execute pathogen#infect()
syntax on
filetype plugin indent on

set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
set number
set gfn=Monaco:h11
set hlsearch
set incsearch

colorscheme railscasts

cd /Users/Derek/Sites/
